### ISSUE TITLE
Feature Suggestion: Bulk Action Creation using Wildcard

### ISSUE THREAD

**Issue by GlennSchner** [azuravian/playnite-LocalLibrary#2]
In default Playnite, you can create bulk actions by selecting multiple games & going to the Edit tab. While the path & working directory fields support variables such as {Name} & {InstallDir}, they don't support regular expressions or wildcard syntax as far as I'm aware.

So if I want to use Local Library to import 50 games at once, I have to create or edit Install Actions for each game, choosing an exe manually for each one. If there was a way to smartly create actions in bulk or by automation it would save potential hours of work. 

For an example use case, you could set the bulk path to \{Name}\*.exe or setup_{Name}.exe with instructions to ignore case & treat underscores as spaces.

**Comment by GlennSchner** [comment]
Hopefully this is actually doable & useful to other people. Also I hope my explanation makes sense.

**Comment by azuravian** [comment]
So, I've been putting together something that I hope will address this for you.  Basically, it allows you to set 1 or more folders that hold your installers.  The supported structure is that each subfolder underneath the specified folder represents 1 game.  It will go through compare the paths to games you already have configured and any that aren't represented will be added with the game name being the folder name and the action or rom (depending on preference) being matched to one of the following:

1. An EXE named setup or install
2. An ISO with any name
3. An archive (7z, rar, zip) with any name

Then you just download the metadata using whatever preferences you already use in PN and everything should be ready to go.

**Comment by azuravian** [comment]
Closing this as resolved with v1.5.0
